# Site Info
title: '데꾸벅'
tagline: ''
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: http://techbug.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: TECHBUG
  description: A passionate <strong>front-end engineer and pattern searcher</strong>.
  gravatar: d7365ecfc6d43c2375b57daf713f5fcd # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/techbugkim
    github:    https://github.com/techbug
    # facebook:  <hide>
    twitter:   https://twitter.com/atprompt
    #weibo:     <hide>
    email:     http://www.google.com/recaptcha/mailhide/d?k=01cqy08ysKO4FMFViMSk2vXQ==&c=QwW0zIgzpCnDJCAd4C3eWE7dCSFjldJsXrXlS0nyCM8=

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'http://techbug.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'techbug' # leave blank if you don't want disqus

